* Projet EmacsBoost

Bienvenue dans le projet EmacsBoost ! Ce dépôt GitHub regroupe des ressources et
des fichiers pour améliorer votre expérience avec Emacs et vous aider
à maîtriser ses fonctionnalités. Explorez les différents fichiers et dossiers
disponibles pour maximiser vos compétences dans l'utilisation d'Emacs.

** Contenu du projet

Entre autres :

2. docs/emacs-boost-exercices.org

   Un fichier Org qui propose des exercices pour renforcer vos compétences dans
   l'utilisation d'EmacsBoost.

   Parcourez ces exercices pour améliorer votre maîtrise d'Emacs.

6. lisp/emacsboost.el

   Le fichier source Emacs Lisp pour la configuration EmacsBoost.

   Plongez dans le code pour découvrir comment EmacsBoost personnalise Emacs
   pour une utilisation plus fluide.

** Comment contribuer

Si vous avez des idées d'amélioration, des suggestions ou des correctifs
à apporter, n'hésitez pas à ouvrir une issue ou à soumettre une /pull
request/. Votre contribution est la bienvenue pour faire évoluer EmacsBoost et
aider d'autres utilisateurs à tirer le meilleur parti d'Emacs.

Amusez-vous à explorer EmacsBoost et à améliorer vos compétences Emacs !
